baseURL = "https://www.techwitch.space"
theme = "risotto"
title = "techwitch"
author = "gothintheshell"
copyright = "Posts are © [gothintheshell](https://github.com/m-pent) 2025. This blog is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/?)."
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 3

[params]
noindex = false
customCSS = ["css/techwitch.css"]
theme.palette = "techwitch"

# Sidebar: about/bio
[params.about]
title = "techwitch"
description = "Finding the magic in technology."
# unicode/emoji logo:
logo = "🪄🐌"
# or use an image:
#logo_image = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/m-pent"

[[params.socialLinks]]
icon = "fa-brands fa-mastodon"
title = "Mastodon"
url = "https://infosec.exchange/@cosyskog"

[[params.socialLinks]]
icon = "fa-brands fa-bluesky"
title = "Bluesky"
url = "https://bsky.app/profile/gothintheshell.bsky.social"


[menu]

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    url = "/projects/"
    weight = 5

  [[menu.main]]
    identifier = "privacy"
    name = "privacy"
    url = "/privacy/"
    weight = 10


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true